In [1]:
import pandas as pd

print(pd.__version__)

3.0.5

In [2]:
import pandas as pd

logon = pd.read_csv("../data/logon.csv")
file_activity = pd.read_csv("../data/file.csv")
device = pd.read_csv("../data/device.csv")

print("Logon:", logon.shape)
print("File:", file_activity.shape)
print("Device:", device.shape)

Logon: (854859, 5)
File: (445581, 6)
Device: (405380, 5)

In [3]:
print("LOGON COLUMNS:")
print(logon.columns.tolist())

print("\nFILE COLUMNS:")
print(file_activity.columns.tolist())

print("\nDEVICE COLUMNS:")
print(device.columns.tolist())

LOGON COLUMNS:
['id', 'date', 'user', 'pc', 'activity']

FILE COLUMNS:
['id', 'date', 'user', 'pc', 'filename', 'content']

DEVICE COLUMNS:
['id', 'date', 'user', 'pc', 'activity']

In [4]:
print("LOGON DATA TYPES:")
print(logon.dtypes)

print("\nFILE DATA TYPES:")
print(file_activity.dtypes)

print("\nDEVICE DATA TYPES:")
print(device.dtypes)

LOGON DATA TYPES:
id          str
date        str
user        str
pc          str
activity    str
dtype: object

FILE DATA TYPES:
id          str
date        str
user        str
pc          str
filename    str
content     str
dtype: object

DEVICE DATA TYPES:
id          str
date        str
user        str
pc          str
activity    str
dtype: object

In [5]:
print("LOGON MISSING VALUES:")
print(logon.isnull().sum())

print("\nFILE MISSING VALUES:")
print(file_activity.isnull().sum())

print("\nDEVICE MISSING VALUES:")
print(device.isnull().sum())

LOGON MISSING VALUES:
id          0
date        0
user        0
pc          0
activity    0
dtype: int64

FILE MISSING VALUES:
id          0
date        0
user        0
pc          0
filename    0
content     0
dtype: int64

DEVICE MISSING VALUES:
id          0
date        0
user        0
pc          0
activity    0
dtype: int64

In [6]:
logon.head()

                         id                 date     user       pc activity
0  {X1D9-S0ES98JV-5357PWMI}  01/02/2010 06:49:00  NGF0157  PC-6056    Logon
1  {G2B3-L6EJ61GT-2222RKSO}  01/02/2010 06:50:00  LRR0148  PC-4275    Logon
2  {U6Q3-U0WE70UA-3770UREL}  01/02/2010 06:53:04  LRR0148  PC-4124    Logon
3  {I0N5-R7NA26TG-6263KNGM}  01/02/2010 07:00:00  IRM0931  PC-7188    Logon
4  {D1S0-N6FH62BT-5398KANK}  01/02/2010 07:00:00  MOH0273  PC-6699    Logon

In [7]:
file_activity.head()

,id,date,user,pc,filename,content
0,{L9G8-J9QE34VM-2834VDPB},01/02/2010 07:23:14,MOH0273,PC-6699,EYPC9Y08.doc,D0-CF-11-E0-A1-B1-1A-E1 during difficulty over...
1,{H0W6-L4FG38XG-9897XTEN},01/02/2010 07:26:19,MOH0273,PC-6699,N3LTSU3O.pdf,25-50-44-46-2D carpenters 25 landed strait dis...
2,{M3Z0-O2KK89OX-5716MBIM},01/02/2010 08:12:03,HPH0075,PC-2417,D3D3WC9W.doc,D0-CF-11-E0-A1-B1-1A-E1 union 24 declined impo...
3,{E1I4-S4QS61TG-3652YHKR},01/02/2010 08:17:00,HPH0075,PC-2417,QCSW62YS.doc,D0-CF-11-E0-A1-B1-1A-E1 becoming period begin ...
4,{D4R7-E7JL45UX-0067XALT},01/02/2010 08:24:57,HSB0196,PC-8001,AU75JV6U.jpg,FF-D8

In [8]:
device.head()

                         id                 date     user       pc    activity
0  {J1S3-L9UU75BQ-7790ATPL}  01/02/2010 07:21:06  MOH0273  PC-6699     Connect
1  {N7B5-Y7BB27SI-2946PUJK}  01/02/2010 07:37:41  MOH0273  PC-6699  Disconnect
2  {U1V9-Z7XT67KV-5649MYHI}  01/02/2010 07:59:11  HPH0075  PC-2417     Connect
3  {H0Z7-E6GB57XZ-1603MOXD}  01/02/2010 07:59:49  IIW0249  PC-0843     Connect
4  {L7P2-G4PX02RX-7999GYOY}  01/02/2010 08:04:26  IIW0249  PC-0843  Disconnect

In [9]:
logon["date"] = pd.to_datetime(logon["date"])
file_activity["date"] = pd.to_datetime(file_activity["date"])
device["date"] = pd.to_datetime(device["date"])

print("LOGON DATE RANGE:")
print(logon["date"].min(), "to", logon["date"].max())

print("\nFILE DATE RANGE:")
print(file_activity["date"].min(), "to", file_activity["date"].max())

print("\nDEVICE DATE RANGE:")
print(device["date"].min(), "to", device["date"].max())

LOGON DATE RANGE:
2010-01-02 06:49:00 to 2011-05-17 06:43:35

FILE DATE RANGE:
2010-01-02 07:23:14 to 2011-05-16 23:22:34

DEVICE DATE RANGE:
2010-01-02 07:21:06 to 2011-05-16 23:22:34

In [10]:
print("Unique users in logon:", logon["user"].nunique())
print("Unique users in file:", file_activity["user"].nunique())
print("Unique users in device:", device["user"].nunique())

Unique users in logon: 1000
Unique users in file: 264
Unique users in device: 265

In [11]:
print("Top 10 users by logon activity:")
print(logon["user"].value_counts().head(10))

Top 10 users by logon activity:
user
WPR0368    3470
AJF0370    3267
CBB0365    3256
BAL0044    3146
IBB0359    3086
LBC0356    3053
EIS0041    3052
DMG0358    3038
HDS0367    3035
UIR0043    2860
Name: count, dtype: int64

In [12]:
print("Top 10 users by file activity:")
print(file_activity["user"].value_counts().head(10))

Top 10 users by file activity:
user
HSB0196    11627
AJF0370    11053
LBH0942    10889
DLM0051    10673
HPH0075     9323
MOH0273     9306
DBB0384     8543
ZKS0899     8537
THR0873     8525
VIA0063     8524
Name: count, dtype: int64

In [13]:
print("Top 10 users by device activity:")
print(device["user"].value_counts().head(10))

Top 10 users by device activity:
user
AJF0370    8502
IBB0359    7852
LBH0942    7785
HSB0196    7595
DLM0051    7533
OBH0499    7395
IIW0249    6735
KKW0879    6501
HPH0075    6345
JDF0593    6296
Name: count, dtype: int64

## Threat Scenarios Analyzed

- **Scenario ID/name**: Scenario 1
  - **Malicious user ID**: CSF0929
  - **Start date**: 07/01/2010 01:24:58
  - **End date**: 07/16/2010 06:52:00
  - **Malicious activity**: User who did not previously use removable drives or work after hours begins logging in after hours, using a removable drive, and uploading data to wikileaks.org. Leaves the organization shortly thereafter.

- **Scenario ID/name**: Scenario 2
  - **Malicious user ID**: CCH0959
  - **Start date**: 08/02/2010 10:34:31
  - **End date**: 09/30/2010 15:04:03
  - **Malicious activity**: User begins surfing job websites and soliciting employment from a competitor. Before leaving the company, they use a thumb drive (at markedly higher rates than their previous activity) to steal data.

- **Scenario ID/name**: Scenario 3
  - **Malicious user ID**: KTW0365
  - **Start date**: 07/08/2010 11:51:00
  - **End date**: 07/09/2010 20:54:16
  - **Malicious activity**: System administrator becomes disgruntled. Downloads a keylogger and uses a thumb drive to transfer it to his supervisor's machine. The next day, he uses the collected keylogs to log in as his supervisor and send out an alarming mass email, causing panic in the organization. He leaves the organization immediately.